### ISSUE TITLE
Find and implement examples for SPLOMs

### ISSUE THREAD

**Issue by flekschas** [flekschas/piling.js#90]
Another useful example for interactive visual piling could be SPLOMs.

We already discovered this [diabetes dataset](https://www.kaggle.com/uciml/pima-indians-diabetes-database) from this [plotly article on SPLOMs](https://medium.com/plotly/what-is-a-splom-chart-make-scatterplot-matrices-in-python-8dc4998921c3).

We should create an example for this diabetes dataset and also try to find larger examples with maybe up to several hundred scatterplots.

**Todo:**
- [x] Download and prepare the diabetes dataset
- [ ] Implement an interactive scatterplot visualization with D3 that supports interactions with the dots (this will come in handy once we have the _live rendering mode_ implemented.
- [ ] Set up a piling.js example using the SVG renderer
- [ ] Find larger examples

**Comment by eeeeenchanted** [comment]
You can download the diabetes dataset [here](https://drive.google.com/drive/folders/1TnaGCggp37r5Wp1eTO3O4OxxGkJflD9C). Also, I already found some other SPLOM data and put them in this folder before I left Harvard 😄

**Comment by flekschas** [comment]
Okay great! I forgot about those. Is the data is the same format in all three cases?

**Comment by eeeeenchanted** [comment]
Yes I think so. The [data.cvs](https://drive.google.com/open?id=1Zzeig08j0x33wjP4xFxwadZ2RcwUYRq3) one is pretty large.

**Comment by flekschas** [comment]
Hi Lucy, can you please download the world bank data and create scatterplots for 2 out of the 3 axes with D3? I think we can reuse the existing D3 code for that.

What we should do is to split the countries into continents (asia, europe, africa, australia, north america, south america) so that but use common axes for all groups. Then for each year we should render a separate scatterplot.

Finally, the aggregator should simply combine the time steps for each country. And a specialized renderer should then plot the scatterplot as usual but connect the different timesteps. Last but not least, the curve should have a color gradient similar to what Benjamin used in his time curves plot so that the user can find out how time progressed as they pile things up.
